/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsOfflineRouteImport } from './routes/settings.offline'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as ReportSubmitRouteImport } from './routes/report.submit'
import { Route as ReportCaptureRouteImport } from './routes/report.capture'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOfflineRoute = SettingsOfflineRouteImport.update({
  id: '/settings/offline',
  path: '/settings/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSubmitRoute = ReportSubmitRouteImport.update({
  id: '/report/submit',
  path: '/report/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCaptureRoute = ReportCaptureRouteImport.update({
  id: '/report/capture',
  path: '/report/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/navigation': typeof NavigationRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/report/$id': typeof ReportIdRoute
  '/report/capture': typeof ReportCaptureRoute
  '/report/submit': typeof ReportSubmitRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/offline': typeof SettingsOfflineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/navigation': typeof NavigationRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/report/$id': typeof ReportIdRoute
  '/report/capture': typeof ReportCaptureRoute
  '/report/submit': typeof ReportSubmitRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/offline': typeof SettingsOfflineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/navigation': typeof NavigationRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/edit': typeof ProfileEditRoute
  '/report/$id': typeof ReportIdRoute
  '/report/capture': typeof ReportCaptureRoute
  '/report/submit': typeof ReportSubmitRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/offline': typeof SettingsOfflineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/community'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/navigation'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/profile/edit'
    | '/report/$id'
    | '/report/capture'
    | '/report/submit'
    | '/settings/notifications'
    | '/settings/offline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/community'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/navigation'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/profile/edit'
    | '/report/$id'
    | '/report/capture'
    | '/report/submit'
    | '/settings/notifications'
    | '/settings/offline'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/community'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/navigation'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/profile/edit'
    | '/report/$id'
    | '/report/capture'
    | '/report/submit'
    | '/settings/notifications'
    | '/settings/offline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NavigationRoute: typeof NavigationRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReportIdRoute: typeof ReportIdRoute
  ReportCaptureRoute: typeof ReportCaptureRoute
  ReportSubmitRoute: typeof ReportSubmitRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOfflineRoute: typeof SettingsOfflineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/offline': {
      id: '/settings/offline'
      path: '/settings/offline'
      fullPath: '/settings/offline'
      preLoaderRoute: typeof SettingsOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/submit': {
      id: '/report/submit'
      path: '/report/submit'
      fullPath: '/report/submit'
      preLoaderRoute: typeof ReportSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/capture': {
      id: '/report/capture'
      path: '/report/capture'
      fullPath: '/report/capture'
      preLoaderRoute: typeof ReportCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NavigationRoute: NavigationRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReportIdRoute: ReportIdRoute,
  ReportCaptureRoute: ReportCaptureRoute,
  ReportSubmitRoute: ReportSubmitRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOfflineRoute: SettingsOfflineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
